apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::930832106480:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-eIxczaDksake
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

  mapRoles: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::930832106480:user/somayya
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-16T05:24:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1186"
  uid: 0fe40a11-85f6-4f1e-b938-33deaaa966da

